baseURL = "https://ashishdasnurkar.com"
languageCode = "en-us"
title = "Ashish Dasnurkar"
theme = "zen"

[params]
  cookieConsent = true       # Show cookie consent form, default false.
  contact = "ashish.dasnurkar@gmail.com"
  copyright = "This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/)"
  feedlinks = true
  footer = "Powered by [Hugo](https://gohugo.io/) and the [Zen theme](https://github.com/frjo/hugo-theme-zen)."
  mobileMenu = true
  poweredby = false
  sidebar = true
[permalinks]
  posts = "/blog/:year/:month/:day/:title/"
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4  
